export const allStatusTranslations = {
    EMITTED: 'Эмитирован',
    APPLIED: 'Нанесён',
    INTRODUCED: 'В обороте',
    WRITTEN_OFF: 'Списан',
    RETIRED: 'Выбыл',
    WITHDRAWN: 'Выбыл',
    DISAGGREGATION: 'Расформирован',
    DISAGGREGATED: 'Расформирован',
    APPLIED_NOT_PAID: 'Не оплачен',
    IN_GRAY_ZONE: 'В Серой зоне',
    EMPTY: 'Значение отсутствует',
    RESERVED_NOT_USED: 'Зарезервировано. Не использовать',
    INDIVIDUAL: 'КиЗ индивидуализирован',
    NON_INDIVIDUAL: 'Не индивидуализирован',
    WAIT_SHIPMENT: 'Ожидает приёмку товара',
    EXPORTED: 'Используется для документов экспорта',
    LOAN_RETIRED: 'Выведен из оборота по договору рассрочки',
    LOST_INVENTORY: 'Не найдены по итогу инвентаризации',
    REMARK_RETIRED: 'Перемаркирован',
    WAIT_TRANSFER_TO_OWNER: 'Ожидает передачу собственнику',
    WAIT_REMARK: 'Ожидает перемаркировку',
    RETIRED_CANCELLATION: 'Списан / Аннулирован',
    FTS_RESPOND_NOT_OK: 'Отрицательное решение ФТС',
    FTS_RESPOND_WAITING: 'Ожидает подтверждение ФТС',
    FTS_CONTROL: 'На контроле ФТС',
    EAS_RESPOND_NOT_OK: 'Отрицательное решение ЕАЭС',
    EAS_RESPOND_WAITING: 'Ожидает подтверждение ЕАЭС',
    CONNECT_TAP: 'Подключён к оборудованию для розлива',
    PRIM_RESPONSE_WAITING: 'Обрабатывается',
    MOVING_BY_UD: 'Отгружен',
    NEW: 'Зарегистрирован',
    PRODUCTION: 'Производство',
    VALIDATION_FAILED: 'Ошибка в проверке',
    'IN PROGRESS': 'Заказ в процессе выполнения',
    SUCCESS: 'Заказ выполнен',
    ERROR: 'При выполнении заказа возникла ошибка',
    RESULT_EXPIRED: 'Заказ устарел',
    IN_PROGRESS: 'Проверяется',
    CHECKED_OK: 'Обработан',
    CHECKED_NOT_OK: 'Обработан с ошибками',
    PROCESSING_ERROR: 'Техническая ошибка',
    UNDEFINED: 'Не определён',
    ACCEPTED: 'Принят',
    CANCELLED: 'Аннулирован',
    WAIT_ACCEPTANCE: 'Ожидает приёмку',
    PARSE_ERROR: 'Обработан с ошибками',
    WAIT_PARTICIPANT_REGISTRATION: 'Ожидает регистрации участника в ГИС МТ',
    WAIT_FOR_CONTINUATION: 'Проверяется',
    REGISTERED: 'Зарегистрирован',
    PRE_REGISTERED: 'Предварительная регистрация началась',
    NOT_REGISTERED: 'Не зарегистрирован',
    REMOVED: 'Удален',
    RESTORED: 'Восстановлен',
    BLOCKED: 'Заблокирован',
    draft: 'Черновик',
    published: 'Опубликована',
    archived: 'В архиве',
    0: 'Черновик',
    1: 'Ожидается отправка',
    2: 'Доставлен (подпись не требуется)',
    3: 'Доставлен (требуется подпись)',
    4: 'Подписан',
    5: 'Отклонен',
    6: 'Отозван',
    7: 'Уточнён',
    8: 'Требуется уточнение',
    9: 'Ошибка в подписи',
    10: 'Ошибка доставки',
    11: 'Ожидается отправка',
    12: 'Просмотрен (подпись не требуется)',
    13: 'Просмотрен (требуется подпись)',
    14: 'Требуется уточнение (запрос на уточнение просмотрен)',
    15: 'Отклонен (запрос просмотрен)',
    16: 'Запрошено аннулирование',
    17: 'Ожидается аннулирование',
    18: 'Аннулирован',
    19: 'В аннулировании отказано',
} as const;

export type StatusKey = keyof typeof allStatusTranslations;

export const invalidStatus: StatusKey[] = [
    'RETIRED',
    'WITHDRAWN',
    'DISAGGREGATION',
    'WRITTEN_OFF',
    'DISAGGREGATED',
    'APPLIED_NOT_PAID',
];
